In [26]:
import torch
import numpy as np
from torch import Tensor

In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
my_list = [
    [1,2,3,4,5],
    [6,7,8,9,10]
]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.01427952, 0.13275366, 0.53269422, 0.32581997],
       [0.66159328, 0.77813609, 0.88479351, 0.57597497],
       [0.79921828, 0.10788405, 0.53518025, 0.54343553]])

In [6]:
np1.dtype

dtype('float64')

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.4094,  0.7262,  1.0487,  1.2545],
        [-0.6900, -0.3849,  0.8478,  0.5092],
        [ 0.1244,  0.2607,  1.0873,  0.5972]])

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
np1 = np.random.randint(low=1, high=4, size=(3,3))
np1

array([[1, 1, 1],
       [1, 1, 2],
       [1, 2, 3]])

In [17]:
tensor_np = torch.tensor(np1)
tensor_np

tensor([[1, 1, 1],
        [1, 1, 2],
        [1, 2, 3]], dtype=torch.int32)

In [18]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Reshape if we do not know the number of items, using -1

my_torch2 = my_torch2.reshape(5, -1)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [27]:
my_torch3 = my_torch2.reshape(5,2)
my_torch3

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [28]:
my_torch2[2]= 777
my_torch2

tensor([[  0,   1],
        [  2,   3],
        [777, 777],
        [  6,   7],
        [  8,   9]])

In [29]:
my_torch3

tensor([[  0,   1],
        [  2,   3],
        [777, 777],
        [  6,   7],
        [  8,   9]])

In [49]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [50]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [51]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [52]:
torch.subtract(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [53]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [55]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [56]:
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [57]:
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [58]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [59]:
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

In [61]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [63]:
tensor_a += tensor_b
tensor_a

tensor([16, 20, 24, 28])